### ISSUE TITLE
Issue using IntraACL with Visual Editor MediaWiki Extension

### ISSUE THREAD

**Issue by SamWMTaylor** [mediawiki4intranet/IntraACL#53]
Hello,

We have installed IntraACL and it appears to be working fine except when we try to use Visual Editor on a page already protected by IntraACL.

As soon as we hit the 'Edit' button we get an error saying

"Error loading data from server: parsoidserver-http-bad-status: 404: Did not find page revisions for Systems/Photoshop.  Would you like to retry?"

The issue goes away if I grant 'All Users' full access to the protected page we are trying to edit.  This isn't ideal as a normal user will be able to view a protected page whilst it's being edited.

We also use a plugin called PwAuthPlugin which pulls down passwords/authentication directly from Active Directory.

Visual Editor relies on a server called Parsoid, this (and all the processes it governs like, nodejs, npm and pm2 etc) is governed by the root user on our Centos server.

I just wanted to find out if anyone else has experienced this issue before and has a fix.  With all the different combinations of Extensions we have I'm not confident there's a fix for this and we'll have to use the workaround above.

Thanks

**Comment by vitalif** [comment]
Do you have `'forwardCookies' => true` in $wgVirtualRestConfig['modules']['parsoid'] in your LocalSettings.php?

**Comment by vitalif** [comment]
from my point of view VE & parsoid is a rather perverted and useless thing ))) but of course I also tried it out ))

**Comment by SamWMTaylor** [comment]
Hello Vitaliy,

Thanks for getting back.

Yes it's already set to true:

$wgVirtualRestConfig['modules']['parsoid']['forwardCookies'] = true;

I'm inclined to agree, Parsoid is a very difficult and unintuitive thing to set up.

Just for info, here's the rest of our LocalSettings.php options connected to Visual Editor and Parsoid:


require_once "$IP/extensions/VisualEditor/VisualEditor.php";

// Enable by default for everybody
$wgDefaultUserOptions['visualeditor-enable'] = 1;

// Don't allow users to disable it
$wgHiddenPrefs[] = 'visualeditor-enable';

// OPTIONAL: Enable VisualEditor's experimental code features
$wgDefaultUserOptions['visualeditor-enable-experimental'] = 1;

// URL to the Parsoid instance
// MUST NOT end in a slash due to Parsoid bug
// Use port 8142 if you use the Debian package
$wgVisualEditorParsoidURL = 'http://127.0.0.1:8000';

// Interwiki prefix to pass to the Parsoid instance
// Parsoid will be called as $url/$prefix/$pagename
$wgVisualEditorParsoidPrefix = 'cgiwiki';

# See if we can get rid of the 'add a comment dialog'
$wgVisualEditorUseChangeTagging = false;

// This feature requires a non-locking session store. The default session store will not work and
// will cause deadlocks (connection timeouts from Parsoid) when trying to use this feature.
$wgSessionsInObjectCache = true;

// WARNING: ONLY enable this on private wikis and ONLY IF you understand the SECURITY IMPLICATIONS
// of sending Cookie headers to Parsoid over HTTP. For security reasons, it is strongly recommended
// that $wgVisualRestConfig['modules']['parsoid']['url'] be pointed to localhost if this setting is enabled.
$wgVirtualRestConfig['modules']['parsoid']['forwardCookies'] = true;

If you have any other thoughts do let me know.

thanks again

**Comment by vitalif** [comment]
Hm... it seems parsoid does not forward user cookie back to MediaWiki when requesting revision content. So IntraACL of course denies access to anonymous user.

this could be fixed by removing (&& !User::isEveryoneAllowed('read')) condition at line 79 of ApiVisualEditor.php in VisualEditor extension, but when I remove it on my wiki, Parsoid is unable to do MW api requests. I tried to understand WHY it's unable, but in last 20 minutes I didn't succeed O_O the HTTP request from nodejs to MediaWiki (apache2 behind nginx) just hangs, it looks like nodejs closes the connection by itself before receiving the request!!! The same request done with browser or with netcat completes without problem.

The request is:

GET /wiki/api.php?format=json&action=query&meta=siteinfo&siprop=namespaces%7Cnamespacealiases%7Cmagicwords%7Cfunctionhooks%7Cextensiontags%7Cgeneral%7Cinterwikimap%7Clanguages%7Cprotocols%7Cspecialpagealiases&rawcontinue=1 HTTP/1.1
X-Request-ID: null
User-Agent: Parsoid/0.4.1+git
Connection: close
Cookie: wikiEditor-0-toolbar-section=advanced; mediawikiUserID=2; mediawikiUserName=VitaliyFilippov; mediawikiToken=...........; mediawiki_session=............
host: yourcmc.ru

**Comment by anshum17** [comment]
So do we have any conclusion? Can we use Visualeditor with IntraACL or not?
I am facing "error loading data from server: 500 parsoidserver-http"

**Comment by belonesox** [comment]
Yes, we have to patch one line in Visual Editor. I just preparing to publish deployement scripts of MediaWiki4Intranet by Vagrant+Ansible, where IntraACL and VisualEditor works together.
https://github.com/belonesox/mediawiki4intranet-vagrant-ansible

**Comment by anshum17** [comment]
"I just preparing to publish deployement scripts of MediaWiki4Intranet by
Vagrant+Ansible"

Did not understand this.

Also I have 1 more query. There is one "File List" page. This page is not
protected and anybody can see the media files. Ideally files on protected
page should also be protected, but it is not happening.

So am I missing something here or is it a developing feature?

Thanks,
Anshum

**Comment by vitalif** [comment]
> "I just preparing to publish deployement scripts of MediaWiki4Intranet by Vagrant+Ansible"

That was slightly offtopic.

Stas should push his fix to https://github.com/mediawiki4intranet/mediawiki-extensions-VisualEditor/commits/master and then switch the repository in configs/mediawiki4intranet.ini

Afaik it's the same fix as I told above:
>removing (&& !User::isEveryoneAllowed('read')) condition at line 79 of ApiVisualEditor.php

This looked like the proper fix from the beginning, but it didn't work when I checked it previous time. I'll recheck if it works with newer versions of VE.

> This page is not protected and anybody can see the media files.

First of all, are you saying the page is NOT protected? :) obviously anyone can read it if it's not protected :)

Secondly, files in MediaWiki aren't "attachments to pages", they are globally named and independent entities. So if you want to protect files with IntraACL, you should create ACLs for File: namespace, files themselves or place them into a protected category.

**Comment by anshum17** [comment]
Hi,

After making suggested changes i.e. removing code from line 79. I am still
facing the same issue. :(

On browser I am getting 'error loading data from
server:500:parsoidserver-http:HTTP 500'.

And in parsoid logs:
{"code":"rvaccessdenied","info":"The current user is not allowed to read
Scrapbooking"}
at TemplateRequest.ApiRequest._errorObj
(/usr/lib/parsoid/src/lib/mw/ApiRequest.js:340:9)
    at TemplateRequest._handleJSON
(/usr/lib/parsoid/src/lib/mw/ApiRequest.js:529:16)
    at TemplateRequest.ApiRequest._handleBody
(/usr/lib/parsoid/src/lib/mw/ApiRequest.js:458:7)
    at TemplateRequest.ApiRequest._requestCB
(/usr/lib/parsoid/src/lib/mw/ApiRequest.js:413:8)
    at Request.self.callback
(/usr/lib/parsoid/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous>
(/usr/lib/parsoid/node_modules/request/request.js:1063:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous>
(/usr/lib/parsoid/node_modules/request/request.js:1009:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)

**Comment by vitalif** [comment]
Oh shit! I've found the problem with "hanging" nodejs mediawiki API requests with this fix applied.
The problem is PHP's session lock mechanism! When someone calls session_start() PHP locks it exclusively and unlocks only on session_write_close() or when the request ends. The lock itself isn't bad - the session data is overwritten every time so you definitely end up with race conditions if you don't lock it. The bad point is that PHP programmers (and MediaWiki authors are no exception) usually don't bother about clever session handling and just keep it open for the whole request. This basically means such PHP setups can't handle more than 1 request for 1 user in parallel. And look what happens when you use parsoid?
- browser sends an API request to MediaWiki (PHP)
- PHP sends a request to Parsoid **and always forwards user cookies with the above fix (!)**
- Parsoid send some request back to PHP as it needs some info from it **and it includes the forwarded cookies**...
- ...so PHP gets another request from the same user while the previous is still active and the session is still locked.
Bang, a deadlock.
And it's not very simple to fix because we need to improve MediaWiki's session handling to fix it (i.e. patch mediawiki core). I'll of course make this patch and include it in our bundle (https://github.com/mediawiki4intranet/core) but I'm not giving any promises about getting it merged to upstream.

**Comment by belonesox** [comment]
>Did not understand this.
I mean «IntraACL+VisualEditor» looks working in this installation
https://github.com/mediawiki4intranet/mediawiki4intranet-vagrant-ansible

**Comment by vitalif** [comment]
OK, I've committed the session lock fix into mediawiki4intranet bundle. I.e. you can use `repo.php` to install it from https://github.com/mediawiki4intranet/configs (check readme)
To install the fix manually you need this patch to mediawiki core: https://github.com/mediawiki4intranet/core/commit/72331616d69a706e1321e3e817c2730814bef417 (this one is for 1.26), and also patches to ConfirmEdit and OpenID extensions if you have them installed (or they'll be broken): https://github.com/mediawiki4intranet/ConfirmEdit/commit/be1cc8bd5b7702f2de753484d8da191b495557b2 and https://github.com/mediawiki4intranet/OpenID/commit/5425b2a0b4e6520fd5241369fb6abaf43efc423c
need this patch to VisualEditor: https://github.com/mediawiki4intranet/mediawiki-extensions-VisualEditor/commit/cfa72745a7d75f0dc661976dc0918d19d13aa418 (or just install it from here: https://github.com/mediawiki4intranet/mediawiki-extensions-VisualEditor/commits/REL1_26_INTRAACL)

**Comment by centaure** [comment]
I need to get IntraACL+MW1.27+VisualEditor working. (MW1.26 is too old now).
Using your 1.27 patch, I have IntraACL+MW1.27 working. But VisualEditor is NOT working.

If I simply download VE from your repo https://github.com/mediawiki4intranet/mediawiki-extensions-VisualEditor/commits/REL1_27 (commit/9da5996c0ede52598e6a06b68b2f98c0253e86cf) and place it under the extensions/VisualEditor folder the  VE is completely unresponsive. I am guessing problem is with the VE submodules /var/lib/wiki/extensions/VisualEditor/lib/ve/src/ve.js. Now if update the submodules like this:  git submodule update --init
then it starts showing same 404 error again. It does not fix any problems. 

Any help or a bit more detailed step-by-step instructions?

**Comment by Mayzie** [comment]
@vitalif 

Is this still relevant for 1.27? I noticed there were several deprecation hints in the functions you were patching (and they were radically different).

**Comment by vitalif** [comment]
I'm pretty sure yes. Functions may be different, but I don't think something changed in MW session handling... In fact, the problem is funny: everyone uses PHP and nobody usually cares about session locks :)

**Comment by Mayzie** [comment]
Seems like, at least for 1.27 and onwards, they are in the process of overhauling their session management system, so a lot of those patches mentioned in [your comment](https://github.com/mediawiki4intranet/IntraACL/issues/53#issuecomment-248879119) are irrelevant :-( Which is a shame as I am still experiencing deadlocks within PHP when using Visual Editor + IntraACL.

**Comment by Mayzie** [comment]
@vitalif 

It appears those patches are no longer necessary for MediaWiki >= 1.27. The bug I was experiencing was completely unrelated. :-)
